# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to aliyun
      uses: simontunnat/action-maven-deploy@v1
      with:
        username: ${{ secrets.GEEK_REPO_USERNAME }}
        password: $${{ secrets.GEEK_REPO_SECRET }}
        repository: https://packages.aliyun.com/maven/repository/2012569-snapshot-C6Wvk0
      
